name: Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0
  succeed:
    uses: ./.github/workflows/ci-workflow.yml
